### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'

### ISSUE THREAD

**Issue by jetijeti** [clyra/mqtt-zwift#1]
I got an Issue running your mqtt-zwift:

> python mqtt-zwift.py
> Traceback (most recent call last):
>   File "mqtt-zwift.py", line 41, in <module>
>     if check_online(world.players):
>   File "C:\Users\jeti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\zwift\world.py", line 21, in players
>     return self.request.json('/relay/worlds/{}'.format(self.world_id))
>   File "C:\Users\jeti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\zwift\request.py", line 33, in json
>     headers = self.get_headers(accept_type='application/json')
>   File "C:\Users\jeti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\zwift\request.py", line 27, in get_headers
>     "Authorization": "Bearer " + self.get_access_token()
>   File "C:\Users\jeti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\zwift\auth.py", line 75, in get_access_token
>     self.update_token_data()
>   File "C:\Users\jeti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\zwift\auth.py", line 55, in update_token_data
>     self.access_token_expiration = now + self.expires_in - 5
> TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'

 I is related to the zwift/auth.py module. I tried fiddeling with it but could not dig deeper...

**Comment by jetijeti** [comment]
my bad, zwift was not running
